version: "3.9"

services:
  mosquitto-broker:
    image: eclipse-mosquitto:latest
    hostname: mosquitto-broker
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "2883:2883"
    volumes:
      - ./broker/config:/mosquitto/config
    networks:
      - hands_on

  machine:
    image: node:lts
    hostname: iot-machine
    container_name: iot-machine
    restart: unless-stopped
    build: ./machine
    working_dir: /machine
    volumes:
      - ./machine:/machine
    command: "npm install"
    command: "npm start"
    depends_on:
      - mosquitto-broker
    networks:
      - hands_on

  database-mysql:
    image: mysql
    restart: always
    hostname: database-mysql
    container_name: database-mysql
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=abc123!
      - MYSQL_DATABASE=hands_on
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - hands_on

  app:
    image: node:lts
    hostname: app
    container_name: app
    restart: unless-stopped
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    command: "npm install"
    command: "npm start"
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=abc123!
      - MYSQL_DATABASE=hands_on
      - MYSQL_PORT=3306
    depends_on:
      database-mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - hands_on


networks:
  hands_on:
    name: hands_on
    driver: bridge